name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  APP_PATH: node-app/src
  AWS_REGION: us-east-1
  CODEDEPLOY_APPLICATION_NAME: node-app-codedeploy
  CODEDEPLOY_DEPLOYMENT_GROUP_NAME: node-app-codedeploy
  CONTAINER_NAME: node-app
  CONTAINER_PORT: 5000
  ECR_REPOSITORY_NAME: node-app
  ECS_CLUSTER_NAME: my-ecs-cluster
  ECS_SERVICE_NAME: node-app
  ECS_TASK_DEFINITION_FILE: task-definition.json
  TERRAFORM_APP_PATH: node-app/infra
  TERRAFORM_PLATFORM_PATH: platform

jobs:
  # Platform should reside in another repository.
  platform-terraform-plan:
    name: Platform - Terraform plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: |
          cd "$TERRAFORM_PLATFORM_PATH"
          terraform init

      - name: Terraform validate
        run: |
          cd "$TERRAFORM_PLATFORM_PATH"
          terraform validate -no-color

      - name: Terraform plan
        run: |
          cd "$TERRAFORM_PLATFORM_PATH"
          terraform plan -no-color


  platform-terraform-apply:
    name: Platform - Terraform apply
    needs:
      - platform-terraform-plan
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: |
          cd "$TERRAFORM_PLATFORM_PATH"
          terraform init

      - name: Terraform apply
        run: |
          cd "$TERRAFORM_PLATFORM_PATH"
          terraform apply -no-color -auto-approve

  app-terraform-plan:
    name: App - Terraform plan
    needs:
      - platform-terraform-apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: |
          cd "$TERRAFORM_APP_PATH"
          terraform init

      - name: Terraform validate
        run: |
          cd "$TERRAFORM_APP_PATH"
          terraform validate -no-color

      - name: Terraform plan
        run: |
          cd "$TERRAFORM_APP_PATH"
          terraform plan -no-color

  app-terraform-apply:
    name: App - Terraform apply
    needs:
      - app-terraform-plan
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: |
          cd "$TERRAFORM_APP_PATH"
          terraform init

      - name: Terraform apply
        run: |
          cd "$TERRAFORM_APP_PATH"
          terraform apply -no-color -auto-approve

  app-build-and-publish:
    name: App - Build and publish
    needs:
      - app-terraform-apply
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Github -> Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          cd "$APP_PATH"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Get task definition
        id: get-task-definition
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecs describe-task-definition \
            --task-definition "$ECS_SERVICE_NAME" \
            --query taskDefinition > "$ECS_TASK_DEFINITION_FILE"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_FILE }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Print task definition
        id: print-task-definition
        env:
          TASK_DEFINITION_PATH: ${{ steps.task-def.outputs.task-definition }}
        run: |
          cat "$TASK_DEFINITION_PATH"

      - name: Create appspec file
        id: create-appspec-file
        run: |
          echo '{ "version": 0.0, "Resources": [ { "TargetService": { "Type": "AWS::ECS::Service", "Properties": { "TaskDefinition": "ARN_WILL_BE_FILLED_ON_CICD_PIPELINE", "LoadBalancerInfo": { "ContainerName": "$CONTAINER_NAME", "ContainerPort": "$CONTAINER_PORT" } } } } ] }' | envsubst > appspec.json
          cat appspec.json

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
          codedeploy-appspec: appspec.json
          codedeploy-application: ${{ env.CODEDEPLOY_APPLICATION_NAME }}
          codedeploy-deployment-group: ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }}
